---
trigger: short
title: Short Report
description: Howie Short Progress Report
surfaces:
  - issue
steps:
  - type: form
    style: embedded
    actions:
      submit: Submit
    body:
      - type: dropdown
        attributes:
          id: trending
          label: Trending
          options:
            - label: "🟢 on track"
              value: "🟢 on track"
            - label: "🟡 at risk"
              value: "🟡 at risk"
            - label: "🔴 high risk"
              value: "🔴 high risk"
            - label: "⚪ inactive"
              value: "⚪ inactive"
            - label: "⚪ not planned"
              value: "⚪ not planned"
            - label: "🟣 done"
              value: "🟣 done"
      - type: input
        attributes:
          id: target_date
          label: Target date
          format: date
      - type: textarea
        attributes:
          id: update
          label: Update
          placeholder: A few words on how it's going
  - type: fill
    submit_form: true
    template_path: .github/commands/howie-short-report.liquid
