---
name: weekly-updates
description: PF Weekly Update
body:
- type: dropdown
  attributes: 
    label: Weekly Status Update
    options: 
    - label: "\U0001F7E2 Green (all good, on track to complete this quarter)"
      value: "\U0001F7E2 Green"
    - label: "\U0001F7E1 Yellow (some concerns, but under control and still expect to complete this quarter)"
      value: "\U0001F7E1 Yellow"
    - label: "\U0001F534 Red (blocked,help needed to complete this quarter)"
      value: "\U0001F534 Red"
- type: input
  attributes:
    label: Target date
    format: date
- type: textarea
  attributes:
    label: Update
    placeholder: What deliverables have landed or decisions made? Please share links to artifacts when available. 
- type: textarea
  attributes: 
    label: Up Next
    placeholder: What deliverables or milestones are next?
- type: textarea
  attributes: 
    label: Risks and Mitigations (optional)
    placeholder: What are any risks or blockers surfaced? What is the mitigation plan? What help is needed? 
